<?php
/** @var \MylSoft\Baner\Block\Baner $block */

$baners = $block->getBaner();
?>

<div id="mylsoft-baner">
<?php if ($baners->getSize()): ?>
    <ul class="mylsoft-baner">
        <?php foreach ($baners as $baner): ?>
            <li>
                    <?php if ($baner->getUrl()): ?>
                        <a href="<?= $baner->getUrl(); ?>" class="content" title="<?= $baner->getName(); ?>" target="_blank">
                    <?php endif; ?>
                    <img src="<?= $baner->getImageUrl(); ?>" alt="<?= $baner->getName(); ?>" width="100%"/>
                    <h3><?= $baner->getName() ?></h3>
                    <?php if ($baner->getUrl()): ?>
                        </a>
                    <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
    <script type="text/javascript">
        require(['jquery', 'slick'], function ($) {
            $('.mylsoft-baner').slick({
                dots: false,
                arrows: false,
                autoplay: true,
                autoplaySpeed: 2000,
            });
        });
    </script>
<?php endif; ?>
</div>
