<?php

namespace MylSoft\Custom\Block\Address\Form\Edit;

use Magento\Customer\Api\Data\AddressInterface;
use Magento\Framework\Exception\NoSuchEntityException;
use Magento\Framework\View\Element\Template;
use Magento\Customer\Api\AddressRepositoryInterface;
use Magento\Customer\Api\Data\AddressInterfaceFactory;
use Magento\Customer\Model\Session;

class Custom extends Template
{
    /**
     * @var AddressInterface
     */
    private $_address;

    /**
     * @var AddressRepositoryInterface
     */
    private $_addressRepository;

    /**
     * @var AddressInterfaceFactory
     */
    private $_addressFactory;

    /**
     * @var Session
     */
    private $_customerSession;

    /**
     * Custom constructor.
     * @param Template\Context $context
     * @param AddressRepositoryInterface $addressRepository
     * @param AddressInterfaceFactory $addressInterfaceFactory
     * @param Session $session
     * @param array $data
     */
    public function __construct(
        Template\Context $context,
        AddressRepositoryInterface $addressRepository,
        AddressInterfaceFactory $addressInterfaceFactory,
        Session $session,
        array $data = [])
    {
        parent::__construct($context, $data);
        $this->_addressFactory = $addressInterfaceFactory;
        $this->_addressRepository = $addressRepository;
        $this->_customerSession = $session;
    }

    protected function _prepareLayout()
    {
        $addressId = $this->getRequest()->getParam('id');

        try {
            $this->_address = $this->_addressRepository->getById($addressId);
            if($this->_address->getCustomerId() != $this->_customerSession->getCustomerId())
            {
                $this->_address = null;
            }
        } catch (NoSuchEntityException $e
        {
            $this->_address = null;
        }

        if(null === $this->_address)
        {
            $this->_address = $this->addressFactory->create();
        }

        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    protected function _toHtml()
    {
        $customWidgetBlock = $this->getLayout()->createBlock(
            'MylSoft\Custom\Block\Customer\Widget\Custom'
        );
        return $customWidgetBlock->toHtml();
    }
}
